# from https://gitlab.gwdg.de/tobi_public/quarto_test/-/blob/main/.gitlab-ci.yml
image: python:3.10

variables:
  QUARTO_VERSION: 1.6.40
  BASENAME: rs_jf_20250123_eods_cookbook
  BRANCH_NAME: "main"

before_script:
  - python -V

pages:
  script:
    - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
    - dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb
    - quarto add --no-prompt kapsner/authors-block
    - quarto install tinytex
    - pip install jupyter
    - quarto check install
    - quarto check jupyter
    - make
  artifacts:
    paths:
      - public
  only:
    - main
